Fix teragrep exec syslog stream command not working with subsequent commands when using host and port parameters
teragrep/pth_03 pull request #67
Opened 2024-08-14 12:36 UTC by 51-code

Fixes #66.

Basically the issue was that the port number was recognizable only in the grammar mode "COMMAND_TERAGREP_MODE_IP", but when the parser read it, it didn't pop the grammar mode back to the mode where it can recognize other tokens again (like the pipe token).

Created unit tests for the command and refactored the whole unit test file to not throw exceptions in tests because that is not good practice.

2024-08-14 12:42 UTC, eemhu approved these changes

2024-08-21 07:13 UTC, kortemik requested changes

2024-08-21 07:13 UTC, kortemik commented on src/main/antlr4/imports/COMMAND_TERAGREP_MODE.g4
>  COMMAND_TERAGREP_IP: DIGIT(COMMAND_TERAGREP_MODE_COMMA)DIGIT(COMMAND_TERAGREP_MODE_COMMA)DIGIT(COMMAND_TERAGREP_MODE_COMMA)DIGIT -> popMode;
prefix tokens in COMMAND_TERAGREP_IP mode with COMMAND_TERAGREP_IP_MODE_

2024-08-21 07:36 UTC, kortemik approved these changes

2024-08-21 07:36 UTC, merged