Create pull_request_template.md
teragrep/pth_03 pull request #74
Opened 2024-09-04 11:37 UTC by ronja-ui

Added PR template

2024-10-25 08:50 UTC, kortemik requested changes

2024-10-25 08:50 UTC, kortemik commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
please add rat-plugin exception

2025-04-07 07:33 UTC, ronja-ui commented on .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
done

2025-04-07 08:10 UTC, StrongestNumber9 approved these changes
lgtm, template is same as in template repo and properly excluded in rat plugin

2025-04-07 08:10 UTC, merged